name = "belautocenter-nextjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "belautocenter-nextjs-prod"

# Development environment
[env.development]
name = "belautocenter-nextjs-dev"

# Environment variables
[vars]
NODE_ENV = "production"

# Build configuration
[build]
command = "npm run pages:build"