name = "belautocenter-worker"
main = "image-cache-worker.js"
compatibility_date = "2025-08-14"

# Переменные окружения
[vars]
FIREBASE_PROJECT_ID = "belauto-f2b93" # Обновите на правильный ID проекта

# R2 Bucket конфигурация
[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "belautocenter"
preview_bucket_name = "belautocenter-dev" # для разработки

# Конфигурация для рабочей среды
[env.production]
name = "belautocenter-worker-prod"
routes = [
  { pattern = "images.belautocenter.by/*", zone_name = "belautocenter.by" }
]

# Конфигурация для разработки
[env.development]
name = "belautocenter-worker-dev"
vars = { FIREBASE_PROJECT_ID = "belauto-f2b93" }

# Конфигурация для тестирования
[env.staging]
name = "belautocenter-worker-staging"

# Trigger на определенные события
[triggers]
crons = ["0 0 * * *"] # Ежедневно в полночь для очистки кэша или других задач

# Настройки для локальной разработки
[dev]
port = 8787
local_protocol = "http"
