name = "autobel-cache-worker"
main = "image-cache-worker.js"
compatibility_date = "2024-12-09"

# Переменные окружения
[vars]
FIREBASE_PROJECT_ID = "belauto-f2b93"

# Добавляем поддержку Cloudflare R2
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "belautocenter"

[env.production]
name = "autobel-cache-worker"
routes = [
  { pattern = "images.belautocenter.by/*", zone_name = "belautocenter.by" },
  { pattern = "cache.belautocenter.by/*", zone_name = "belautocenter.by" }
]

[env.development]
name = "autobel-cache-worker-dev"
